### ISSUE TITLE
To add: Noblesse

### ISSUE THREAD

**Issue by ardianta** [ardianta/anime-for-dev#52]
- https://noblesse.fandom.com/wiki/Noblesse_Wiki

**Comment by vivian-dai** [comment]
Can I take this issue?

**Comment by ardianta** [comment]
Yes, you can. I will assign it to you.

**Comment by vivian-dai** [comment]
Hey, could you take a look at #94 thanks!

**Comment by ardianta** [comment]
Thanks @vivian-dai
